import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarMenu } from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="bg-zinc-900 text-white"
      >
        <div className="z-50">
      <NavbarMenu/>
        </div>
        {children}
        <div>

        <Footer/>
        </div>
      </body>
    </html>
  );
}
